stages:
  - compile
  - deploy

# Compile documentation
compilation:
  stage: compile
  only:
    - master
  image: atlas/analysisbase:21.2.30
  tags:
    - cvmfs
  before_script:
    - source /home/atlas/release_setup.sh
  script:
    - pip install mkdocs
    - mkdocs build
  artifacts:
    paths:
      - site/
    expire_in: 1 hour

# Deploy to EOS
deployment:
  stage: deploy
  only:
    - master
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  script:
    - deploy-eos
  before_script: []
  after_script: []
