stages:
  - compile
  - deploy

# Compile documentation
compilation:
  stage: compile
  only:
    - master
  tags:
    - cvmfs
  variables:
    ATLAS_LOCAL_ROOT_BASE: /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
  script:
    - alias setupATLAS="source ${ATLAS_LOCAL_ROOT_BASE}/user/atlasLocalSetup.sh"
    - setupATLAS
    - lsetup "lcgenv -p LCG_93 x86_64-slc6-gcc62-opt Python"
    - pip install mkdocs
    - mkdocs build
  artifacts:
    paths:
      - site/
    expire_in: 1 hour

# Deploy to EOS
deployment:
  stage: deploy
  only:
    - master
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  script:
    - deploy-eos
  before_script: []
  after_script: []
